### ISSUE TITLE
//to-do list:

### ISSUE THREAD

**Issue by KnightsOfTheSeaA** [KnightsOfTheSeaA/Robot6736#1]
*/  in order to move things with our code we have to make our to-do list so here is what we need to do in the next week:

- [ ]   **finish gyro angle code.**

- [ ]   **start with image processing.**

- [ ]    as soon as we get either one of the subsystems working on the robot we need to start thinking about how we are going to deal with it in our code. **anyway start thinking in advanced about the subsystems included** (ball shooting, ball grabbing, autonomous driving and handling with problems, etc). 

- [ ]   **finding new crew members with knowledge on c++ .**

- [ ]    start teaching crew members without farther knowledge on c++.

- [ ]   **getting more computers for algorithm writers + installing eclipse on all.**   /*
